site :opscode

cookbook 'git'
cookbook 'build-essential'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database'
cookbook 'xml'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'git@github.com:fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'nginx'
cookbook 'imagemagick'
cookbook 'simple_iptables', git:"git@github.com:rtkwlf/cookbook-simple-iptables.git"
cookbook 'rails_book_cookbook', path: './site-cookbooks/rails_book_cookbook'
