# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec feature)

## Uncomment to clear the screen before every task
# clearing :on

## Guard internally checks for changes in the Guardfile and exits.
## If you want Guard to automatically start up again, run guard in a
## shell loop, e.g.:
##
##  $ while bundle exec guard; do echo "Restarting Guard..."; done
##
## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), the you will want to move the Guardfile
## to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard :shell do
   watch(%r{app/controllers/.+\.rb}) { `ripper-tags -e -R -f TAGS` }
   watch(%r{app/models/.+\.rb}) { `ripper-tags -e -R -f TAGS` }
   watch(%r{app/helpers/.+\.rb}) { `ripper-tags -e -R -f TAGS` }
   watch(%r{app/models/.+\.rb}) { `erd --attributes=foreign_keys,primary_keys,content,timestamp --filename=E-Rdiagram --filetype=png` }
end

guard 'livereload' do
   watch( /^app\/(controllers|models|helpers)\/.+\.rb$/ )
   watch(%r{app/views/.+\.(erb|haml|slim)$})
   watch(%r{public/.+\.(css|js|html)})
   watch(%r{config/locales/.+\.yml})
   # Rails Assets Pipeline
   watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html|png|jpg))).*}) { |m| "/assets/#{m[3]}" }
end

# Usage:
#     guard :foreman, <options hash>
#
# Possible options:
# * :concurreny - how many of each type of process you would like to run (default is, sensibly, one of each)
# * :env - one or more .env files to load
# * :procfile - an alternate Procfile to use (default is Procfile)
# * :port - an alternate port to use (default is 5000)
# * :root - an alternate application root
guard :foreman do
  # Rails example - Watch controllers, models, helpers, lib, and config files
#  watch( /^app\/(controllers|models|helpers)\/.+\.rb$/ )
  watch( /^lib\/.+\.rb$/ )
  watch( /^config\/*/ )
end

guard 'yard' do
   watch( /^app\/(controllers|models|helpers)\/.+\.rb$/ )
end

